<a href="https://colab.research.google.com/github/yukimiyazaki/AtCoder/blob/master/Educational_DP_Contest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [A - Frog 1](https://atcoder.jp/contests/dp/tasks/dp_a)

---


N
  個の足場があります。 足場には 
1
,
2
,
…
,
N
 と番号が振られています。 各 
i
 (
1
≤
i
≤
N
) について、足場 
i
 の高さは 
h
i
 です。

最初、足場 
1
 にカエルがいます。 カエルは次の行動を何回か繰り返し、足場 
N
 まで辿り着こうとしています。

足場 
i
 にいるとき、足場 
i
+
1
 または 
i
+
2
 へジャンプする。 このとき、ジャンプ先の足場を 
j
 とすると、コスト 
|
h
i
−
h
j
|
 を支払う。
カエルが足場 
N
 に辿り着くまでに支払うコストの総和の最小値を求めてください。

In [0]:
N = int(input())
hlist = list(map(int, input().split()))


4
10 30 40 20


In [0]:
cost = [-1 for _ in range(N)]
cost[0] = 0
cost[1] = abs(hlist[1] - hlist[0])
cost

[0, 20, -1, -1]

In [0]:
#再帰
"""
def function(n)
if 終了条件 return 初項
return function(n-1)を処理したもの
"""
def dp(n):
  print(n)
  if n==0: return cost[0]
  if n==1: return cost[1]
  else: return min(dp(n-1)+abs(hlist[n]-hlist[n-1]), dp(n-2)+abs(hlist[n]-hlist[n-2]))

In [0]:
for i in range(N):
  cost[i] = dp(i)

0
1
2
1
0
3
2
1
0
1


In [0]:
cost

[0, 20, 30, 30]

In [0]:
print(cost[-1])

30


In [0]:
N = int(input())
hlist = list(map(int, input().split()))

#再帰
"""
def function(n)
if 終了条件 return 初項
return function(n-1)を処理したもの
"""
def dp(n):
  if n==0: return 0
  if n==1: return abs(hlist[1] - hlist[0])
  else: return min(dp(n-1)+abs(hlist[n]-hlist[n-1]), dp(n-2)+abs(hlist[n]-hlist[n-2]))

print(dp(N-1))

In [0]:
N = int(input())
hlist = list(map(int, input().split()))
cost = [-1 for _ in range(N)]
 
def dp(n):
  if n==0: return 0
  if n==1: return abs(hlist[1] - hlist[0])
  else: return min(cost[n-1]+abs(hlist[n]-hlist[n-1]), cost[n-2]+abs(hlist[n]-hlist[n-2]))
 
for i in range(N):
  cost[i]=dp(i)
print(cost[-1])

In [0]:
cost

[0, 20, 30, 30]

# [B - Frog 2](https://atcoder.jp/contests/dp/tasks/dp_b)

---


N
  個の足場があります。 足場には 
1
,
2
,
…
,
N
 と番号が振られています。 各 
i
 (
1
≤
i
≤
N
) について、足場 
i
 の高さは 
h
i
 です。

最初、足場 
1
 にカエルがいます。 カエルは次の行動を何回か繰り返し、足場 
N
 まで辿り着こうとしています。

足場 
i
 にいるとき、足場 
i
+
1
,
i
+
2
,
…
,
i
+
K
 のどれかへジャンプする。 このとき、ジャンプ先の足場を 
j
 とすると、コスト 
|
h
i
−
h
j
|
 を支払う。
カエルが足場 
N
 に辿り着くまでに支払うコストの総和の最小値を求めてください。



In [0]:
def chmin(a, b): #aとbを入れた時に
    if a > b: return a
    else: return b

In [0]:
chmin(1,2)

2

In [0]:
N,K = map(int,input().split())
hlist = list(map(int, input().split()))
cost = [-1 for _ in range(N)]

5 3
10 30 40 50 20


In [0]:
cost

[-1, -1, -1, -1, -1]

In [0]:
hlist[i]

30

In [0]:
np.zeros(N, dtype="int32")

array([0, 0, 0, 0, 0], dtype=int32)

In [0]:
import numpy as np
h = np.array(hlist)

dp = np.zeros(N, dtype="int32")
 
for i in range(1, N):
    if i < K:
        dp[i] = np.min(dp[:i] + np.abs(h[i]-h[:i]))
    else:
        dp[i] = np.min(dp[i-K:i] + np.abs(h[i]-h[i-K:i]))

In [0]:
dp[0]

0

In [0]:
i=3
np.abs(h[i]-h[:i])

array([40, 20, 10])

In [0]:
dp[:i]

array([ 0, 20, 30], dtype=int32)

In [0]:
print(dp[N - 1])

30


In [0]:
import numpy as np
 
N_K = list(map(int,input().split()))
H = np.array(list(map(int,input().split())))
 
N = N_K[0]
K = N_K[1]
 
dp= np.zeros(N,dtype=np.int)
 
for i in range(1,len(H)):
 
    if i < K:
        dp[i] = np.min(dp[:i] + np.abs(H[i]-H[:i]))
    else:
        dp[i] = np.min(dp[i-K:i] + np.abs(H[i]-H[i-K:i]))
    
print(dp[N - 1])